/*
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIF22ScopeProvider extends DelegatingScopeProvider {
}
