/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.generator;

import com.google.common.collect.Iterators;
import dk.sdu.mmmi.mdsd.math.Assignment;
import dk.sdu.mmmi.mdsd.math.Div;
import dk.sdu.mmmi.mdsd.math.Exp;
import dk.sdu.mmmi.mdsd.math.ExpOp;
import dk.sdu.mmmi.mdsd.math.In;
import dk.sdu.mmmi.mdsd.math.LetEnd;
import dk.sdu.mmmi.mdsd.math.Litteral;
import dk.sdu.mmmi.mdsd.math.MathExp;
import dk.sdu.mmmi.mdsd.math.Minus;
import dk.sdu.mmmi.mdsd.math.Mult;
import dk.sdu.mmmi.mdsd.math.Parenthesis;
import dk.sdu.mmmi.mdsd.math.Plus;
import dk.sdu.mmmi.mdsd.math.Primary;
import dk.sdu.mmmi.mdsd.math.VariableUse;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MathGenerator extends AbstractGenerator {
  private static Map<String, Integer> variables = new HashMap<String, Integer>();
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final MathExp model = Iterators.<MathExp>filter(resource.getAllContents(), MathExp.class).next();
    final Map<String, Integer> result = MathGenerator.compute(model);
    this.displayPanel(result);
  }
  
  public static Map<String, Integer> compute(final MathExp math) {
    final int count = ((Object[])Conversions.unwrapArray(math.getAssignments(), Object.class)).length;
    for (int i = 0; (i < count); i++) {
      {
        final Assignment assignment = math.getAssignments().get(i);
        MathGenerator.variables.put(assignment.getName(), Integer.valueOf(MathGenerator.computeExp(assignment.getExp())));
      }
    }
    return MathGenerator.variables;
  }
  
  public static int computeExp(final Exp exp) {
    int _xblockexpression = (int) 0;
    {
      final int left = MathGenerator.computePrim(exp.getLeft());
      int _switchResult = (int) 0;
      ExpOp _operator = exp.getOperator();
      boolean _matched = false;
      if (_operator instanceof Plus) {
        _matched=true;
        int _computeExp = MathGenerator.computeExp(exp.getRight());
        _switchResult = (left + _computeExp);
      }
      if (!_matched) {
        if (_operator instanceof Minus) {
          _matched=true;
          int _computeExp = MathGenerator.computeExp(exp.getRight());
          _switchResult = (left - _computeExp);
        }
      }
      if (!_matched) {
        if (_operator instanceof Mult) {
          _matched=true;
          int _computeExp = MathGenerator.computeExp(exp.getRight());
          _switchResult = (left * _computeExp);
        }
      }
      if (!_matched) {
        if (_operator instanceof Div) {
          _matched=true;
          int _computeExp = MathGenerator.computeExp(exp.getRight());
          _switchResult = (left / _computeExp);
        }
      }
      if (!_matched) {
        _switchResult = left;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
  
  public static int computePrim(final Primary prim) {
    int _switchResult = (int) 0;
    boolean _matched = false;
    if (prim instanceof Litteral) {
      _matched=true;
      _switchResult = ((Litteral)prim).getValue();
    }
    if (!_matched) {
      if (prim instanceof VariableUse) {
        _matched=true;
        _switchResult = MathGenerator.computeVariableUse(((VariableUse)prim));
      }
    }
    if (!_matched) {
      if (prim instanceof Parenthesis) {
        _matched=true;
        _switchResult = MathGenerator.computeParenthesis(((Parenthesis)prim));
      }
    }
    if (!_matched) {
      _switchResult = 0;
    }
    return _switchResult;
  }
  
  public static int computeVariableUse(final VariableUse use) {
    return (MathGenerator.variables.get(use.getRef().getName())).intValue();
  }
  
  public static int computeParenthesis(final Parenthesis par) {
    return MathGenerator.computeExp(par.getExp());
  }
  
  public static int computeLetEnd(final LetEnd le) {
    return 0;
  }
  
  public static int computeIn(final In in) {
    return 0;
  }
  
  public void displayPanel(final Map<String, Integer> result) {
    String resultString = "";
    Set<Map.Entry<String, Integer>> _entrySet = result.entrySet();
    for (final Map.Entry<String, Integer> entry : _entrySet) {
      String _resultString = resultString;
      String _key = entry.getKey();
      String _plus = ("var " + _key);
      String _plus_1 = (_plus + " = ");
      Integer _value = entry.getValue();
      String _plus_2 = (_plus_1 + _value);
      String _plus_3 = (_plus_2 + "\n");
      resultString = (_resultString + _plus_3);
    }
    JOptionPane.showMessageDialog(null, resultString, "Math Language", JOptionPane.INFORMATION_MESSAGE);
  }
}
