/*
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.ui.tests;

import com.google.inject.Injector;
import lomzt.mdsd.exam.ui.internal.ExamActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IF22UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ExamActivator.getInstance().getInjector("lomzt.mdsd.exam.IF22");
	}

}
