/**
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lomzt.mdsd.exam.iF22.IF22Package#getEnd()
 * @model
 * @generated
 */
public interface End extends Location
{
} // End
