/**
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.iF22;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ending Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lomzt.mdsd.exam.iF22.EndingTarget#getFrom <em>From</em>}</li>
 *   <li>{@link lomzt.mdsd.exam.iF22.EndingTarget#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see lomzt.mdsd.exam.iF22.IF22Package#getEndingTarget()
 * @model
 * @generated
 */
public interface EndingTarget extends EObject
{
  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Location)
   * @see lomzt.mdsd.exam.iF22.IF22Package#getEndingTarget_From()
   * @model
   * @generated
   */
  Location getFrom();

  /**
   * Sets the value of the '{@link lomzt.mdsd.exam.iF22.EndingTarget#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Location value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(Target)
   * @see lomzt.mdsd.exam.iF22.IF22Package#getEndingTarget_Target()
   * @model containment="true"
   * @generated
   */
  Target getTarget();

  /**
   * Sets the value of the '{@link lomzt.mdsd.exam.iF22.EndingTarget#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Target value);

} // EndingTarget
