/**
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.iF22;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lomzt.mdsd.exam.iF22.ExternalCall#getFunc <em>Func</em>}</li>
 *   <li>{@link lomzt.mdsd.exam.iF22.ExternalCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalCall()
 * @model
 * @generated
 */
public interface ExternalCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Func</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' reference.
   * @see #setFunc(ExternalImport)
   * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalCall_Func()
   * @model
   * @generated
   */
  ExternalImport getFunc();

  /**
   * Sets the value of the '{@link lomzt.mdsd.exam.iF22.ExternalCall#getFunc <em>Func</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' reference.
   * @see #getFunc()
   * @generated
   */
  void setFunc(ExternalImport value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link lomzt.mdsd.exam.iF22.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // ExternalCall
