/**
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.iF22;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lomzt.mdsd.exam.iF22.ExternalImport#getName <em>Name</em>}</li>
 *   <li>{@link lomzt.mdsd.exam.iF22.ExternalImport#getParams <em>Params</em>}</li>
 *   <li>{@link lomzt.mdsd.exam.iF22.ExternalImport#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalImport()
 * @model
 * @generated
 */
public interface ExternalImport extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalImport_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lomzt.mdsd.exam.iF22.ExternalImport#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link lomzt.mdsd.exam.iF22.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalImport_Params()
   * @model containment="true"
   * @generated
   */
  EList<Type> getParams();

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' containment reference.
   * @see #setReturnType(Type)
   * @see lomzt.mdsd.exam.iF22.IF22Package#getExternalImport_ReturnType()
   * @model containment="true"
   * @generated
   */
  Type getReturnType();

  /**
   * Sets the value of the '{@link lomzt.mdsd.exam.iF22.ExternalImport#getReturnType <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' containment reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(Type value);

} // ExternalImport
