/**
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.iF22;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lomzt.mdsd.exam.iF22.IF22Package#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
