/*
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.parser.antlr;

import com.google.inject.Inject;
import lomzt.mdsd.exam.parser.antlr.internal.InternalIF22Parser;
import lomzt.mdsd.exam.services.IF22GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IF22Parser extends AbstractAntlrParser {

	@Inject
	private IF22GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIF22Parser createParser(XtextTokenStream stream) {
		return new InternalIF22Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Story";
	}

	public IF22GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IF22GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
