/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ExternalCall#getFunc <em>Func</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.ExternalCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalCall()
 * @model
 * @generated
 */
public interface ExternalCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Func</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' reference.
   * @see #setFunc(ExternalDefinition)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalCall_Func()
   * @model
   * @generated
   */
  ExternalDefinition getFunc();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.ExternalCall#getFunc <em>Func</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' reference.
   * @see #getFunc()
   * @generated
   */
  void setFunc(ExternalDefinition value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getExternalCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // ExternalCall
