/**
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IF22IdeModule extends AbstractIF22IdeModule {
}
