/*
 * generated by Xtext 2.26.0
 */
package lomzt.mdsd.exam.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class IF22UiModule extends AbstractIF22UiModule {
}
